version: '3.8'

services:
  mysql:
    image: mysql:8.0.40
    container_name: compliance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compliance_management_system
      MYSQL_USER: compliance_user
      MYSQL_PASSWORD: compliance_pass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: compliance-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  mysql_data:
  minio-data: 