version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: compliance_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: compliance_user
      MYSQL_PASSWORD: compliance_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    container_name: compliance-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  mysql_data:
  minio-data: 