spring:
  datasource:
    url: jdbc:mysql://localhost:3306/compliance_db
    username: compliance_user
    password: compliance_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket: compliance-bucket

logging:
  level:
    root: INFO
    com.example.project: DEBUG 