spring:
  datasource:
    organization:
      url: jdbc:mysql://localhost:3307/organization_db?useUnicode=true&characterEncoding=utf8mb4&characterSetResults=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&connectionCollation=utf8mb4_unicode_ci
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    code-master:
      url: jdbc:mysql://localhost:3307/code_master_db?useUnicode=true&characterEncoding=utf8mb4&characterSetResults=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&connectionCollation=utf8mb4_unicode_ci
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    document:
      url: jdbc:mysql://localhost:3307/document_db?useUnicode=true&characterEncoding=utf8mb4&characterSetResults=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&connectionCollation=utf8mb4_unicode_ci
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    framework:
      url: jdbc:mysql://localhost:3307/framework_db?useUnicode=true&characterEncoding=utf8mb4&characterSetResults=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&connectionCollation=utf8mb4_unicode_ci
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    audit:
      url: jdbc:mysql://localhost:3307/audit_db?useUnicode=true&characterEncoding=utf8mb4&characterSetResults=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&connectionCollation=utf8mb4_unicode_ci
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    training:
      url: jdbc:mysql://localhost:3307/training_db?useUnicode=true&characterEncoding=utf8mb4&characterSetResults=utf8mb4&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&connectionCollation=utf8mb4_unicode_ci
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    pool:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          CharSet: utf8mb4
          collation: utf8mb4_unicode_ci
  jooq:
    sql-dialect: MYSQL
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
    encoding: UTF-8

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minio}
  secret-key: ${MINIO_SECRET_KEY:minio123}
  bucket: ${MINIO_BUCKET:compliance-bucket}

logging:
  level:
    root: INFO
    com.example.project: DEBUG
    org.jooq: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    org.springframework.transaction: TRACE 